### ISSUE TITLE
MulterAzureStorage._removeFile fails with ArgumentNullError

### ISSUE THREAD

**Issue by lpfeup** [symphonicc/multer-azure-blob-storage#12]
calls to `MulterAzureStorage._removeFile` fail with the following error:
```
ArgumentNullError: Required argument blob for function deleteBlobIfExists is not defined
```

This line is the culprit:
https://github.com/symphonicc/multer-azure-blob-storage/blob/9d6e3d7e0e8bba16e4dd922862964cdef6b05f37/src/MulterAzureStorage.ts#L254

`MulterAzureStorage._deleteBlobIfExists` should use `file.blobName` instead of `file.filename`, since `filename` is a property specific to multer disk storage (https://github.com/expressjs/multer/blob/master/storage/disk.js)

**Comment by Sliverb** [comment]
Fixed thanks to @lpfeup
