### ISSUE TITLE
Publish the package

### ISSUE THREAD

**Issue by galkin** [symphonicc/multer-azure-blob-storage#16]
@Sliverb, Could you update lib and/or publish new version for #11 ?

**Comment by galkin** [comment]
@Sliverb, any updates?

**Comment by galkin** [comment]
@Sliverb, any updates?

**Comment by galkin** [comment]
@Sliverb , just friendly riminder

**Comment by mpth** [comment]
Also waiting for an update of the npm package so we can use the changes in #11

**Comment by Sliverb** [comment]
Latest version is now published
