### ISSUE TITLE
npm audit reports "Arbitrary Code Execution" vulnerability

### ISSUE THREAD

**Issue by soulchild** [symphonicc/multer-azure-blob-storage#21]
This package depends on `azure-storage` which in turn depends on a highly vulnerable version of `underscore` (Arbitrary Code Execution): https://www.npmjs.com/advisories/1674

`azure-storage` has already been patched and will hopefully be released in the coming days: https://github.com/Azure/azure-storage-node/pull/677
 
I don't have high hopes this module will ever get a new release though… 😞 Are you still active, @Sliverb?

**Comment by railsstudent** [comment]
azure-storage 2.10.4 was released yesterday.  Upgrade the version of the dependency to 2.10.4, run npm audit and the warnings go away.
